### PR TITLE
Add bindings for arm64 Linux (aarch64-unknown-linux-gnu)

### PR DESCRIPTION
**Pull request by eitsupi**
Related to extendr/rextendr#241

### CODE REVIEW

**Comment by eitsupi** [comment]
Sorry I don't understand the process, but do we need to make any other edits to add bindings?

```r
> remotes::install_github("extendr/helloextendr#17")
Downloading GitHub repo eitsupi/helloextendr@test-linux-arm64
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpwuLeAZ/remotes1fb3b053964/eitsupi-helloextendr-70b9ba1/DESCRIPTION’ (664ms)
─  preparing ‘helloextendr’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘helloextendr_0.1.0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘helloextendr’ ...
** using staged installation
** libs
rm -Rf helloextendr.so ./rust/target/release/libhelloextendr.a entrypoint.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c entrypoint.c -o entrypoint.o
# In some environments, ~/.cargo/bin might not be included in PATH, so we need
# to set it here to ensure cargo can be invoked. It is appended to PATH and
# therefore is only used if cargo is absent from the user's PATH.
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin" && \
        cargo build --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
   Compiling libR-sys v0.3.0
   Compiling proc-macro2 v1.0.49
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23
   Compiling syn v1.0.107
   Compiling extendr-engine v0.3.1 (https://github.com/eitsupi/extendr?rev=ab54824f3c125f8937d3d6c7b8c8117984e9dec9#ab54824f)
   Compiling paste v1.0.11
   Compiling extendr-api v0.3.1 (https://github.com/eitsupi/extendr?rev=ab54824f3c125f8937d3d6c7b8c8117984e9dec9#ab54824f)
   Compiling lazy_static v1.4.0
error: failed to run custom build command for `libR-sys v0.3.0`

Caused by:
  process didn't exit successfully: `/tmp/RtmpeFG4a0/R.INSTALL60c1907d7ef/helloextendr/src/./rust/target/release/build/libR-sys-f074e9fc67bc470a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=R_HOME=/usr/local/lib/R
  cargo:r_home=/usr/local/lib/R
  cargo:rustc-link-search=/usr/local/lib/R/lib
  cargo:rustc-link-lib=dylib=R
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h
  cargo:r_version_major=4
  cargo:r_version_minor=2
  cargo:r_version_patch=2
  cargo:r_version_devel=false

  --- stderr
  thread 'main' panicked at 'Cannot find libR-sys bindings file for R 4.2.2false on linux in bindings. Consider compiling with --features use-bindgen.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libR-sys-0.3.0/build.rs:448:13
  stack backtrace:
     0:     0xaaaaaf0208d0 - std::backtrace_rs::backtrace::libunwind::trace::h6e44a2fb2dd84c73
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0xaaaaaf0208d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h5e578600aa1c4065
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0xaaaaaf0208d0 - std::sys_common::backtrace::_print_fmt::h55cffe56f12843ba
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:66:5
     3:     0xaaaaaf0208d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0f2715cfc075c801
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:45:22
     4:     0xaaaaaf040254 - core::fmt::write::h90daa079fb880be4
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/core/src/fmt/mod.rs:1194:17
     5:     0xaaaaaf00f0dc - std::io::Write::write_fmt::h51bd88c505b540b2
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/io/mod.rs:1655:15
     6:     0xaaaaaf011ae4 - std::sys_common::backtrace::_print::h72ceb2f7e4d8c27c
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:48:5
     7:     0xaaaaaf011ae4 - std::sys_common::backtrace::print::h9b2243361359c6e3
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:35:9
     8:     0xaaaaaf011ae4 - std::panicking::default_hook::{{closure}}::h87079f7c17c39952
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:295:22
     9:     0xaaaaaf0117b8 - std::panicking::default_hook::h34bf124572e2f339
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:314:9
    10:     0xaaaaaf012038 - std::panicking::rust_panic_with_hook::he8045df87f72cb21
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:698:17
    11:     0xaaaaaf020bc0 - std::panicking::begin_panic_handler::{{closure}}::h78aeae536cae259d
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:588:13
    12:     0xaaaaaf0209d8 - std::sys_common::backtrace::__rust_end_short_backtrace::h6ceffde191f66f87
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/sys_common/backtrace.rs:138:18
    13:     0xaaaaaf011c00 - rust_begin_unwind
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
    14:     0xaaaaaeffb4d4 - core::panicking::panic_fmt::hb6ac69ce7975738d
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
    15:     0xaaaaaf005a44 - build_script_build::retrieve_prebuild_bindings::h8aa29a02d949e524
    16:     0xaaaaaf00613c - build_script_build::main::hbea17b0a535fb2b3
    17:     0xaaaaaf000b00 - core::ops::function::FnOnce::call_once::h6210534de1651e83
    18:     0xaaaaaf009288 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd75d68088633f3dc
    19:     0xaaaaaf00212c - std::rt::lang_start::{{closure}}::h65b1c8753d518d22
    20:     0xaaaaaf00d4c0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfcd4710a91fa3f97
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:259:13
    21:     0xaaaaaf00d4c0 - std::panicking::try::do_call::h98ebac5995262944
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:492:40
    22:     0xaaaaaf00d4c0 - std::panicking::try::h5f6a4efe5625efd2
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:456:19
    23:     0xaaaaaf00d4c0 - std::panic::catch_unwind::h4bdaf906bcf7499d
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panic.rs:137:14
    24:     0xaaaaaf00d4c0 - std::rt::lang_start_internal::{{closure}}::hbad6e06c9d245c86
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/rt.rs:128:48
    25:     0xaaaaaf00d4c0 - std::panicking::try::do_call::hd7a8286d9c901c22
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:492:40
    26:     0xaaaaaf00d4c0 - std::panicking::try::h14c27d58a1f2e887
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:456:19
    27:     0xaaaaaf00d4c0 - std::panic::catch_unwind::he2d9d7835162254a
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/panic.rs:137:14
    28:     0xaaaaaf00d4c0 - std::rt::lang_start_internal::h4b1b6b86d118e27f
                                 at /build/rustc-aCh0hl/rustc-1.61.0+dfsg1/library/std/src/rt.rs:128:20
    29:     0xaaaaaf002104 - std::rt::lang_start::h47eb1a7ce2f8b864
    30:     0xaaaaaf006328 - main
    31:     0xffffa06973fc - <unknown>
    32:     0xffffa06974cc - __libc_start_main
    33:     0xaaaaaeffb670 - _start
    34:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
make: *** [Makevars:14: rust/target/release/libhelloextendr.a] Error 101
ERROR: compilation failed for package ‘helloextendr’
* removing ‘/usr/local/lib/R/site-library/helloextendr’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpwuLeAZ/file1fb108d1f8a/helloextendr_0.1.0.tar.gz’ had non-zero exit status
```

**Comment by eitsupi** [comment]
It seems working on Ubuntu 22.04 arm64.

```r
> remotes::install_github("extendr/helloextendr#17")
Downloading GitHub repo eitsupi/helloextendr@test-linux-arm64
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpiBVZo4/remotes1732d6289de/eitsupi-helloextendr-06d0b33/DESCRIPTION’ (710ms)
─  preparing ‘helloextendr’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘helloextendr_0.1.0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘helloextendr’ ...
** using staged installation
** libs
rm -Rf helloextendr.so ./rust/target/release/libhelloextendr.a entrypoint.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c entrypoint.c -o entrypoint.o
# In some environments, ~/.cargo/bin might not be included in PATH, so we need
# to set it here to ensure cargo can be invoked. It is appended to PATH and
# therefore is only used if cargo is absent from the user's PATH.
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin" && \
        cargo build --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
    Updating git repository `https://github.com/eitsupi/extendr`
   Compiling proc-macro2 v1.0.49
   Compiling libR-sys v0.3.0 (https://github.com/eitsupi/libR-sys?rev=de5bdb80bce26879ceb23b7cc66c51421666f1e6#de5bdb80)
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling paste v1.0.11
   Compiling extendr-engine v0.3.1 (https://github.com/eitsupi/extendr?rev=f35068ea0db234d59c2b944d7b54914e92c51e4b#f35068ea)
   Compiling extendr-api v0.3.1 (https://github.com/eitsupi/extendr?rev=f35068ea0db234d59c2b944d7b54914e92c51e4b#f35068ea)
   Compiling lazy_static v1.4.0
   Compiling extendr-macros v0.3.1 (https://github.com/eitsupi/extendr?rev=f35068ea0db234d59c2b944d7b54914e92c51e4b#f35068ea)
   Compiling helloextendr v0.3.0 (/tmp/Rtmpzl74NI/R.INSTALL4ce15016057/helloextendr/src/rust)
    Finished release [optimized] target(s) in 1m 10s
gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o helloextendr.so entrypoint.o -L./rust/target/release -lhelloextendr -L/usr/local/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-helloextendr/00new/helloextendr/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (helloextendr)

> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: aarch64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/aarch64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] processx_3.8.0    compiler_4.2.2    R6_2.5.1          rprojroot_2.0.3   cli_3.6.0         prettyunits_1.1.1
 [7] tools_4.2.2       withr_2.5.0       curl_5.0.0        crayon_1.5.2      remotes_2.4.2     desc_1.4.2
[13] callr_3.7.3       ps_1.7.2          pkgbuild_1.4.0
```

**Review by yutannihilation — APPROVED** [review]
Thanks, this is more complicated than I expected. Great work!

My main concern was the compilation time, but it seems fine. Let's merge.

https://github.com/eitsupi/libR-sys/actions/runs/4244029363/usage

**Comment by eitsupi** [comment]
Thanks for merging this!
Perhaps we should also create a symlink?
https://github.com/extendr/libR-sys/blob/4f5eb99c82af338695e0f213eb0c52f0419c9cad/bindings/bindings-linux-x86_64.rs
